-- MySQL Script generated by MySQL Workbench
-- Mon Sep 28 22:51:42 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema imperio_dos_bichos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imperio_dos_bichos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imperio_dos_bichos` DEFAULT CHARACTER SET utf8 ;
USE `imperio_dos_bichos` ;

-- -----------------------------------------------------
-- Table `imperio_dos_bichos`.`tipo_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imperio_dos_bichos`.`tipo_paciente` (
  `idtipo_paciente` INT NOT NULL AUTO_INCREMENT,
  `especie` VARCHAR(45) NOT NULL,
  `porte` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idtipo_paciente`),
  UNIQUE INDEX `idtipo_paciente_UNIQUE` (`idtipo_paciente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imperio_dos_bichos`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imperio_dos_bichos`.`table2` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imperio_dos_bichos`.`tipo_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imperio_dos_bichos`.`tipo_paciente` (
  `idtipo_paciente` INT NOT NULL AUTO_INCREMENT,
  `especie` VARCHAR(45) NOT NULL,
  `porte` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idtipo_paciente`),
  UNIQUE INDEX `idtipo_paciente_UNIQUE` (`idtipo_paciente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imperio_dos_bichos`.`dono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imperio_dos_bichos`.`dono` (
  `iddono` INT NOT NULL AUTO_INCREMENT,
  `nome_dono` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `telefone_dono` VARCHAR(20) NOT NULL,
  `email_dono` VARCHAR(150) NULL,
  `endereco` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`iddono`),
  UNIQUE INDEX `iddono_UNIQUE` (`iddono` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imperio_dos_bichos`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imperio_dos_bichos`.`paciente` (
  `idpaciente` INT NOT NULL AUTO_INCREMENT,
  `nome_paciente` VARCHAR(200) NOT NULL,
  `nome_dono_paciente` VARCHAR(200) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `situacao` VARCHAR(100) NOT NULL,
  `dono_iddono` INT NOT NULL,
  `tipo_paciente_idtipo_paciente` INT NOT NULL,
  PRIMARY KEY (`idpaciente`, `dono_iddono`, `tipo_paciente_idtipo_paciente`),
  UNIQUE INDEX `idpaciente_UNIQUE` (`idpaciente` ASC) VISIBLE,
  INDEX `fk_paciente_dono1_idx` (`dono_iddono` ASC) VISIBLE,
  INDEX `fk_paciente_tipo_paciente1_idx` (`tipo_paciente_idtipo_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_dono1`
    FOREIGN KEY (`dono_iddono`)
    REFERENCES `imperio_dos_bichos`.`dono` (`iddono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_tipo_paciente1`
    FOREIGN KEY (`tipo_paciente_idtipo_paciente`)
    REFERENCES `imperio_dos_bichos`.`tipo_paciente` (`idtipo_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imperio_dos_bichos`.`veterinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imperio_dos_bichos`.`veterinario` (
  `idveterinario` INT NOT NULL AUTO_INCREMENT,
  `nome_veterinario` VARCHAR(100) NOT NULL,
  `crmv` VARCHAR(20) NOT NULL,
  `especializacao` VARCHAR(100) NOT NULL,
  `telefone_veterinario` VARCHAR(20) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idveterinario`),
  UNIQUE INDEX `idveterinario_UNIQUE` (`idveterinario` ASC) VISIBLE,
  UNIQUE INDEX `crmv_UNIQUE` (`crmv` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imperio_dos_bichos`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imperio_dos_bichos`.`consulta` (
  `idconsulta` INT NOT NULL AUTO_INCREMENT,
  `data_conulta` DATE NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `observacoes_medicas` TEXT NULL,
  `paciente_idpaciente` INT NOT NULL,
  `veterinario_idveterinario` INT NOT NULL,
  PRIMARY KEY (`idconsulta`, `paciente_idpaciente`, `veterinario_idveterinario`),
  UNIQUE INDEX `idconsulta_UNIQUE` (`idconsulta` ASC) VISIBLE,
  INDEX `fk_consulta_paciente1_idx` (`paciente_idpaciente` ASC) VISIBLE,
  INDEX `fk_consulta_veterinario1_idx` (`veterinario_idveterinario` ASC) VISIBLE,
  CONSTRAINT `fk_consulta_paciente1`
    FOREIGN KEY (`paciente_idpaciente`)
    REFERENCES `imperio_dos_bichos`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_veterinario1`
    FOREIGN KEY (`veterinario_idveterinario`)
    REFERENCES `imperio_dos_bichos`.`veterinario` (`idveterinario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
